config/routes.rb
BookReviewer::Application.routes.draw do
  

 

  root :to  => 'books#index'
  resources :books do
    resources :reviews
  end
  
  resources :password_resets
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  

end

app/models/Review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  
  attr_accessible :name, :date, :body
  
  validates :name, :body, :presence  => true
  
  
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :title, :author, :no_of_pages, :isbn
  
  validates :title, :author, :no_of_pages, :presence  => true
 
  has_many :reviews, :dependent  => :destroy
  
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  # attr_accessible :title, :body

  attr_accessible :username, :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :username
  validates_uniqueness_of :email, :username

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :require_login

  def not_authenticated
    redirect_to login_url, :alert => "You must sign up or login to access this page."
  end
  
  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  skip_before_filter :require_login, :only => [:index, :show]
  
  def index
    @books = Book.find(:all)
  end
  
  def new 
    @book = Book.new(params[:book])
  end
  
  def create
    @book = Book.new(params[:book])
    if !@book.save
      render 'new'
    else
      flash[:notice] = "New Book added to collection"
      redirect_to root_path
    end
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if !@book.update_attributes(params[:book])
      render 'edit'
    else
      redirect_to book_path
    end 
  end
  
  def destroy
    @book = Book.find(params[:id])
    if !@book.destroy
      render show
    else
      flash[:notice] = "Book has been terminated"
      redirect_to root_path
    end 
  end
    

  
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login

  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create 
    @user = User.find_by_email(params[:email])

    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user
    # UserMailer.reset_password_email(@user).deliver if @user

    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
  end

  # This is the reset password form.
  def edit
    @user = User.load_from_reset_password_token(params[:id])
    @token = params[:id]
    not_authenticated unless @user
  end

  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:token]
    @user = User.load_from_reset_password_token(params[:token])
    not_authenticated unless @user
    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  skip_before_filter :require_login, :except => [:destroy]
  
  def index
    @book = Book.find(params[:book_id])
    @reviews = Review.find(:all)
  end
  
  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end
  
  def create
    @book = Book.find(params[:book_id])
    @review = @book.reviews.create!(params[:review])
    redirect_to book_path(@book)
  end
  
  def show
    @book = Book.find(params[:book_id])
    @review = Review.find(params[:id])
  end
  
  def edit
    @book = Book.find(params[:book_id])
    @review = Review.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:book_id])
    @review = Review.find(params[:id])
    @review.update_attributes(params[:review])
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to book_path(@book)
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  skip_before_filter :require_login
  
  def new
  end
  
  def create
    user = login(params[:username], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Email or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="header">
<h1>Edit Book</h1>
</div>

<div class="right">
	<% if @book.errors.any? %>
	  <% @book.errors.full_messages.each do |message| %>
	    <li class="validationErrors"><%= message %></li>
	  <% end %>
	<% end %>

	<div class="form">
		<%= form_for @book do |f|%>
		<div class="field">
			<%= f.label :title %>
			<span class="textField"> <%= f.text_field :title %> </span>
		</div>
		<div class="field">
			<%= f.label :author %>
			<span class="textField"><%= f.text_field :author %> </span>
		</div>	
		<div class="field">	
			<%= f.label :no_of_pages %>
			<span class="textField">	<%= f.text_field :no_of_pages %> </span>
		</div>	
		<div class="field">	
			<%= f.label :isbn %>
			<span class="textField">	<%= f.text_field :isbn %></span>
		</div>
		<div>
			<%= f.submit%>
		</div>
	</div>
</div>
<%end%>

app/views/books/index.html.erb
	<h1 id="indexTitle"> Welcome to Book Reviewer </h1>
	<p id="tag"> Meet your next favourite book.... or not</p>
	
<div class="right">
	<div id= "bannerHolder">
		<img id="banner" src="/images/banner.jpeg"/>
	</div>
	


	<% if flash[:notice]%>
 		<%= flash[:notice] %> 
	<%end%>

	<div class=tableBackground>
		<table>
			<tr>
				<th> Book Title</th>
				<th> Book Author</th>
				<th> Number Of Pages</th>
				<th> ISBN</th>
			</tr>
			<tr>
				<% @books.each do |book|%>
			</tr>
			<tr>
				<td> <%= link_to book.title, book_url(book), :method => 'get' %> </td>
				<td> <%=book.author%> </td>
				<td> <%=book.no_of_pages%> </td>
				<td> <%= book.isbn %> </td>
			</tr>
			<% end%>
		</table>

<%= button_to "new",new_book_url, :method  => "get"%>
	</div>


</div>

	

app/views/books/new.html.erb
<div class="header">
	<h1>New Books</h1>
</div>
<div class="right">
<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |message| %>
    <li class="validationErrors"><%= message %></li>
  <% end %>
<% end %>

<div class="form">
	<%= form_for @book do |f|%>
		<div class="field">
			<%= f.label :title %>
			<span class="textField"> <%= f.text_field :title %> </span>
		</div>
		<div class="field">
			<%= f.label :author %>
			<span class="textField"> <%= f.text_field :author %> </span>
		</div>	
		<div class="field">	
			<%= f.label :no_of_pages %>
			<span class="textField"> <%= f.text_field :no_of_pages %> </span>
		</div>	
		<div class="field">	
			<%= f.label :isbn %>
			<span class="textField"> <%= f.text_field :isbn %> </span>
		</div>
		<div>
		<%= f.submit%>
		</div>
	<%end%>
</div>
</div>

app/views/books/show.html.erb
<div class = "header">
<h1>Show Book</h1>
</div>

<div class="right">
<div> title: <%= @book.title%> </div>
<div> author: <%= @book.author%>  </div>
<div> no of pages: <%= @book.no_of_pages%> </div>
<div> ISBN: <%= @book.isbn%> </div>

<%= button_to "edit",edit_book_url, :method  => "get"%>
<%= button_to "delete", @book, :method  => "delete"%>

<h2>Reviews</h2>
<%= render @book.reviews %>
 
<h2>Add a review:</h2>
<%= render "reviews/form"%>
</div>

app/views/identities/new.html.erb
<div class="header">
<h1> New Account </h1>
</div>

<div class="right">
	<%= form_tag "/auth/identity/register" do %>
		<% if @identity  && @identity.errors.any? %>
			<div class="validation_errors">
				<h2><%= pluralize(@identity.errors.count, "error")%> stopped you from creating an account on this painfully awesome page:</h2>
				<ul>
					<% @identity.errors.full_messages.each do |msg|%>
						<li><%= msg%> </li>
						<% end %>
				</ul>
			</div>
		<% end %>
		 <div class="field">  
		    <%= label_tag :name %><br>  
		    <%= text_field_tag :name, @identity.try(:name) %>  
		  </div>  
		  <div class="field">  
		    <%= label_tag :email %><br>  
		    <%= text_field_tag :email, @identity.try(:email) %>  
		  </div>  
		  <div class="field">  
		    <%= label_tag :password %><br>  
		    <%= password_field_tag :password %>  
		  </div>  
		  <div class="field">  
		    <%= label_tag :password_confirmation %><br>  
		    <%= password_field_tag :password_confirmation %>  
		  </div>  
		  <div class="actions"><%= submit_tag "Register" %></div>  
		<% end %>
</div>			

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Ze Amazing Book Reviewer App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id= "main">
<%= yield %>
</div>

<div id="left">
	<% if current_user %>
	  Logged in as <%= current_user.username%>.
	  <%= link_to "Log out", logout_path %>
	<% else %>
	  <%= link_to "Sign up", signup_path %> or
	  <%= link_to "log in", login_path %>.
	<% end %>
	<div><%= link_to "Home", root_path %> </div>
</div>

</body>
</html>

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<div class="right">
	<h1>Choose a new password</h1>
	<%= form_for @user, :url => password_reset_path(@user), :html => {:method => :put} do |f| %>
	  <% if @user.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    
	      <ul>
	      <% @user.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
    
	  <div class="field">
	    <%= f.label :email %><br />
	    <%= @user.email %>
	  </div>
	  <div class="field">
	    <%= f.label :password %><br />
	    <%= f.password_field :password %>
	  </div>
	  <div class="field">
	    <%= f.label :password_confirmation %><br />
	    <%= f.password_field :password_confirmation %>
	    <%= hidden_field_tag :token, @token %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	<% end %>
</div>	

app/views/password_resets/new.html.erb
<div class = "right">
	<%= form_tag password_resets_path, :method => :post do %>
	  <div class="field">
	    <%= label_tag :email %><br />
	    <%= text_field_tag :email %> <%= submit_tag "Reset my password!" %>
	  </div>
	<% end %>
</div>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>

app/views/reviews/_form.html.erb
<%= form_for([@book, @book.reviews.build]) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<p>
  <b>Name:</b>
  <%= review.name %>
</p>
 
<p>
  <b>Review:</b>
  <%= review.body %>
</p>

<%= link_to 'Destroy Comment', [review.book, review],
               :confirm => 'Are you sure?',
               :method => :delete %>

app/views/users/new.html.erb
<div class="right">
	<%= form_for @user do |f| %>
	  <% if @user.errors.any? %>
	    <div class="validation_errors">
	      <h2>Form is invalid</h2>
	      <ul>
	        <% @user.errors.full_messages.each do |message| %>
	          <li><%= message %></li>
	        <% end %>
	      </ul>
	    </div>
	  <% end %>
	  <div class="field">
	    <%= f.label :username %>
	    <%= f.text_field :username %>
	  </div>
	  <div class="field">
	    <%= f.label :email %>
	    <%= f.text_field :email %>
	  </div>
	  <div class="field">
	    <%= f.label :password %>
	    <%= f.password_field :password %>
	  </div>
	  <div class="field">
	    <%= f.label :password_confirmation %>
	    <%= f.password_field :password_confirmation %>
	  </div>
	  <div class="actions"><%= f.submit %></div>
	<% end %>
</div>	